-- OpenToggl PostgreSQL desired-state schema.

create table identity_users (
    id bigserial primary key,
    email text not null unique,
    full_name text not null,
    password_hash text not null,
    api_token text not null unique,
    timezone text not null default 'UTC',
    beginning_of_week integer not null default 0,
    country_id bigint not null default 0,
    default_workspace_id bigint not null default 0,
    state text not null,
    send_product_emails boolean not null default true,
    send_weekly_report boolean not null default true,
    tos_accept_needed boolean not null default true,
    product_emails_disable_code text not null,
    weekly_report_disable_code text not null,
    preferences_animation_opt_out boolean not null default false,
    preferences_collapse_time_entries boolean not null default true,
    preferences_date_format text not null default 'YYYY-MM-DD',
    preferences_duration_format text not null default 'improved',
    preferences_hide_sidebar_right boolean not null default false,
    preferences_is_goals_view_shown boolean not null default true,
    preferences_keyboard_shortcuts_enabled boolean not null default true,
    preferences_language_code text not null default 'en-US',
    preferences_manual_entry_mode text not null default 'timer',
    preferences_manual_mode boolean not null default false,
    preferences_project_shortcut_enabled boolean not null default false,
    preferences_reports_collapse boolean not null default false,
    preferences_send_added_to_project_notification boolean not null default true,
    preferences_send_daily_project_invites boolean not null default true,
    preferences_send_product_release_notification boolean not null default true,
    preferences_send_timer_notifications boolean not null default true,
    preferences_show_time_in_title boolean not null default true,
    preferences_tags_shortcut_enabled boolean not null default false,
    preferences_time_of_day_format text not null default 'h:mm A',
    preferences_alpha_features jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    is_instance_admin boolean not null default false,
    avatar_storage_key text not null default '',
    constraint identity_users_state_check check (state in ('active', 'deactivated', 'deleted', 'pending_verification'))
);

create table identity_sessions (
    id text primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create table identity_email_verification_tokens (
    id bigserial primary key,
    user_id bigint not null unique references identity_users (id) on delete cascade,
    token text not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

create table identity_password_reset_tokens (
    id bigserial primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    consumed_at timestamptz
);

create index identity_password_reset_tokens_user_id_idx on identity_password_reset_tokens (user_id);


create table identity_job_records (
    id bigint generated by default as identity primary key,
    job_name text not null,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index identity_job_records_user_id_idx on identity_job_records (user_id);

create table identity_push_services (
    user_id bigint not null references identity_users (id) on delete cascade,
    fcm_registration_token text not null,
    created_at timestamptz not null default now(),
    primary key (user_id, fcm_registration_token)
);

create index identity_push_services_user_id_idx on identity_push_services (user_id);

create table importing_exports (
    id bigint generated by default as identity primary key,
    scope text not null,
    scope_id bigint not null,
    requested_by bigint not null references identity_users (id) on delete cascade,
    token text not null unique,
    state text not null,
    error_message text not null default '',
    selected_objects jsonb not null default '[]'::jsonb,
    archive_content bytea not null,
    created_at timestamptz not null default now(),
    constraint importing_exports_scope_check check (scope in ('user', 'workspace'))
);

create index importing_exports_scope_idx on importing_exports (scope, scope_id, created_at desc);

create table tenant_organizations (
    id bigint generated by default as identity primary key,
    name text not null
);

create table tenant_workspaces (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    name text not null,
    logo_storage_key text not null default '',
    avatar_storage_key text not null default '',
    default_currency text not null default 'USD',
    default_hourly_rate double precision not null default 0,
    rounding integer not null default 0,
    rounding_minutes integer not null default 0,
    display_policy text not null default 'standard',
    only_admins_may_create_projects boolean not null default false,
    only_admins_may_create_tags boolean not null default false,
    only_admins_see_team_dashboard boolean not null default false,
    projects_billable_by_default boolean not null default false,
    projects_private_by_default boolean not null default false,
    projects_enforce_billable boolean not null default false,
    reports_collapse boolean not null default false,
    public_project_access text not null default 'members',
    report_locked_at text not null default '',
    show_timesheet_view boolean not null default true,
    required_time_entry_fields jsonb not null default '[]'::jsonb,
    suspended_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tenant_workspaces_display_policy_check check (display_policy in ('standard', 'hide_start_end_times')),
    constraint tenant_workspaces_public_project_access_check check (public_project_access in ('members', 'admins'))
);

create index tenant_workspaces_organization_id_idx on tenant_workspaces (organization_id);

create table billing_accounts (
    organization_id bigint primary key references tenant_organizations (id) on delete cascade,
    customer_id text not null default '',
    subscription_plan text not null,
    subscription_state text not null,
    quota_remaining integer not null default 0,
    quota_resets_in_secs integer not null default 0,
    quota_total integer not null default 0
);

create table web_user_homes (
    user_id bigint primary key references identity_users (id) on delete cascade,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade
);

create table membership_organization_members (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    role text not null default 'member',
    state text not null default 'joined',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint membership_organization_members_role_check check (role in ('owner', 'admin', 'member')),
    constraint membership_organization_members_state_check check (state in ('joined', 'inactive'))
);

create unique index membership_organization_members_org_user_key on membership_organization_members (organization_id, user_id);
create index membership_organization_members_user_id_idx on membership_organization_members (user_id);

create table membership_workspace_members (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint references identity_users (id) on delete set null,
    email text not null,
    full_name text not null default '',
    role text not null,
    state text not null,
    is_direct boolean not null default true,
    group_ids bigint[] not null default '{}',
    hourly_rate double precision,
    labor_cost double precision,
    invite_token text,
    invite_token_expires_at timestamptz,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint membership_workspace_members_role_check check (role in ('admin', 'member', 'projectlead', 'teamlead')),
    constraint membership_workspace_members_state_check check (state in ('invited', 'joined', 'disabled', 'restored', 'removed'))
);

create index membership_workspace_members_workspace_id_idx on membership_workspace_members (workspace_id);
create unique index membership_workspace_members_workspace_email_key on membership_workspace_members (workspace_id, lower(email));
create unique index membership_workspace_members_workspace_user_key
    on membership_workspace_members (workspace_id, user_id)
    where user_id is not null;
create unique index membership_workspace_members_invite_token_key
    on membership_workspace_members (invite_token)
    where invite_token is not null;

create table membership_organization_invitations (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    organization_name text not null,
    code text not null unique,
    email text not null,
    sender_user_id bigint not null references identity_users (id) on delete cascade,
    sender_name text not null,
    sender_email text not null,
    recipient_user_id bigint references identity_users (id) on delete set null,
    status text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint membership_organization_invitations_status_check check (status in ('pending', 'accepted', 'rejected'))
);

create index membership_organization_invitations_org_idx on membership_organization_invitations (organization_id, created_at desc);

create table membership_organization_invitation_workspaces (
    invitation_id bigint not null references membership_organization_invitations (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint references identity_users (id) on delete set null,
    workspace_user_id bigint references membership_workspace_members (id) on delete set null,
    primary key (invitation_id, workspace_id)
);

create table catalog_clients (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null,
    notes text not null default '',
    archived boolean not null default false,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_clients_workspace_id_idx on catalog_clients (workspace_id);
create unique index catalog_clients_workspace_name_key on catalog_clients (workspace_id, lower(name));

create table catalog_projects (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    client_id bigint references catalog_clients (id) on delete set null,
    name text not null,
    active boolean not null default true,
    pinned boolean not null default false,
    template boolean not null default false,
    recurring boolean not null default false,
    recurring_period_start date,
    recurring_period_end date,
    color text not null default '#0b83d9',
    is_private boolean not null default true,
    billable boolean not null default false,
    start_date date,
    end_date date,
    estimated_seconds bigint,
    fixed_fee double precision,
    currency text,
    rate double precision,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_projects_workspace_id_idx on catalog_projects (workspace_id);
create index catalog_projects_client_id_idx on catalog_projects (client_id);
create unique index catalog_projects_workspace_name_key on catalog_projects (workspace_id, lower(name));

create table catalog_project_users (
    project_id bigint not null references catalog_projects (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    role text not null default 'member',
    created_at timestamptz not null default now(),
    primary key (project_id, user_id),
    constraint catalog_project_users_role_check check (role in ('admin', 'member'))
);

create index catalog_project_users_user_id_idx on catalog_project_users (user_id);

create table catalog_groups (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    name text not null,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_groups_organization_id_idx on catalog_groups (organization_id);
create unique index catalog_groups_organization_name_key on catalog_groups (organization_id, lower(name));

create table catalog_group_members (
    group_id bigint not null references catalog_groups (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    primary key (group_id, user_id)
);

create index catalog_group_members_user_id_idx on catalog_group_members (user_id);

create table catalog_group_workspaces (
    group_id bigint not null references catalog_groups (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    primary key (group_id, workspace_id)
);

create index catalog_group_workspaces_workspace_id_idx on catalog_group_workspaces (workspace_id);

create table catalog_project_groups (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    project_id bigint not null references catalog_projects (id) on delete cascade,
    group_id bigint not null references catalog_groups (id) on delete cascade
);

create index catalog_project_groups_workspace_id_idx on catalog_project_groups (workspace_id);
create index catalog_project_groups_project_id_idx on catalog_project_groups (project_id);
create index catalog_project_groups_group_id_idx on catalog_project_groups (group_id);
create unique index catalog_project_groups_project_group_key on catalog_project_groups (project_id, group_id);

create table catalog_tags (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null,
    deleted_at timestamptz,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_tags_workspace_id_idx on catalog_tags (workspace_id);
create unique index catalog_tags_workspace_name_key on catalog_tags (workspace_id, lower(name));

create table catalog_tasks (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    project_id bigint references catalog_projects (id) on delete set null,
    name text not null,
    active boolean not null default true,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_tasks_workspace_id_idx on catalog_tasks (workspace_id);
create index catalog_tasks_project_id_idx on catalog_tasks (project_id);
create unique index catalog_tasks_workspace_name_key on catalog_tasks (workspace_id, lower(name));

create table catalog_rates (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    type text not null,
    level text not null,
    level_id bigint not null,
    amount double precision not null,
    creator_id bigint references identity_users (id) on delete set null,
    start_at timestamptz not null,
    end_at timestamptz,
    rate_change_mode text not null,
    project_id bigint references catalog_projects (id) on delete cascade,
    project_user_id bigint,
    planned_task_id bigint references catalog_tasks (id) on delete cascade,
    workspace_user_id bigint references membership_workspace_members (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint catalog_rates_type_check check (type in ('billable_rates', 'labor_costs')),
    constraint catalog_rates_level_check check (level in ('workspace', 'workspace_user', 'project', 'project_user', 'task')),
    constraint catalog_rates_amount_positive_check check (amount > 0),
    constraint catalog_rates_change_mode_check check (rate_change_mode in ('override-all', 'override-current', 'start-today'))
);

create index catalog_rates_lookup_idx on catalog_rates (workspace_id, level, level_id, type, start_at desc);
create index catalog_rates_project_id_idx on catalog_rates (project_id);
create index catalog_rates_planned_task_id_idx on catalog_rates (planned_task_id);
create index catalog_rates_workspace_user_id_idx on catalog_rates (workspace_user_id);

create table tracking_time_entries (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    client_id bigint references catalog_clients (id) on delete set null,
    project_id bigint references catalog_projects (id) on delete set null,
    task_id bigint references catalog_tasks (id) on delete set null,
    description text not null default '',
    billable boolean not null default false,
    start_time timestamptz not null,
    stop_time timestamptz,
    duration_seconds integer not null,
    created_with text not null default '',
    tag_ids bigint[] not null default '{}',
    expense_ids bigint[] not null default '{}',
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index tracking_time_entries_workspace_user_start_idx on tracking_time_entries (workspace_id, user_id, start_time);
create index tracking_time_entries_user_id_idx on tracking_time_entries (user_id);
create index tracking_time_entries_project_id_idx on tracking_time_entries (project_id);
create index tracking_time_entries_task_id_idx on tracking_time_entries (task_id);
create index tracking_time_entries_start_time_idx on tracking_time_entries (start_time);

create table tracking_running_timers (
    user_id bigint primary key references identity_users (id) on delete cascade,
    time_entry_id bigint references tracking_time_entries (id) on delete cascade,
    started_at timestamptz not null default now()
);

create table tracking_expenses (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    time_entry_id bigint references tracking_time_entries (id) on delete set null,
    description text not null default '',
    category text not null default '',
    state text not null default 'draft',
    currency text not null default 'USD',
    total_amount integer not null default 0,
    date_of_expense date not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz,
    constraint tracking_expenses_state_check check (state in ('draft', 'submitted', 'approved', 'rejected', 'reimbursed'))
);

create index tracking_expenses_workspace_id_idx on tracking_expenses (workspace_id);
create index tracking_expenses_user_id_idx on tracking_expenses (user_id);
create index tracking_expenses_time_entry_id_idx on tracking_expenses (time_entry_id);

create table tracking_favorites (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    project_id bigint references catalog_projects (id) on delete set null,
    task_id bigint references catalog_tasks (id) on delete set null,
    description text not null default '',
    billable boolean not null default false,
    public boolean not null default false,
    rank integer not null default 0,
    tag_ids bigint[] not null default '{}',
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index tracking_favorites_workspace_id_idx on tracking_favorites (workspace_id);
create index tracking_favorites_user_id_idx on tracking_favorites (user_id);

create table tracking_goals (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    creator_user_id bigint not null references identity_users (id) on delete cascade,
    name text not null,
    active boolean not null default true,
    billable boolean not null default false,
    comparison text not null default 'gte',
    recurrence text not null default '',
    icon text not null default '',
    target_seconds integer not null default 0,
    start_date date not null,
    end_date date,
    project_ids bigint[] not null default '{}',
    task_ids bigint[] not null default '{}',
    tag_ids bigint[] not null default '{}',
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index tracking_goals_workspace_id_idx on tracking_goals (workspace_id);
create index tracking_goals_user_id_idx on tracking_goals (user_id);

create table tracking_reminders (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    frequency integer not null,
    threshold_hours double precision not null,
    email_reminder_enabled boolean not null default false,
    slack_reminder_enabled boolean not null default false,
    user_ids bigint[] not null default '{}',
    group_ids bigint[] not null default '{}',
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tracking_reminders_frequency_check check (frequency in (1, 7))
);

create index tracking_reminders_workspace_id_idx on tracking_reminders (workspace_id);

create table tracking_timeline_events (
    id bigint generated by default as identity primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    desktop_id text not null default '',
    filename text not null default '',
    title text not null default '',
    start_time integer not null,
    end_time integer not null,
    idle boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index tracking_timeline_events_user_id_idx on tracking_timeline_events (user_id);
create index tracking_timeline_events_start_time_idx on tracking_timeline_events (start_time);

create table governance_alerts (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    project_id bigint references catalog_projects (id) on delete set null,
    receiver_roles jsonb not null default '[]'::jsonb,
    receiver_users jsonb not null default '[]'::jsonb,
    source_kind text not null default '',
    threshold_type text not null default '',
    thresholds jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index governance_alerts_workspace_id_idx on governance_alerts (workspace_id);
create index governance_alerts_project_id_idx on governance_alerts (project_id);

create table governance_audit_logs (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    workspace_id bigint references tenant_workspaces (id) on delete cascade,
    entity_type text not null default '',
    entity_id bigint,
    action text not null default '',
    user_id bigint references identity_users (id) on delete set null,
    source text not null default '',
    request_body text not null default '',
    response_body text not null default '',
    metadata text not null default '',
    created_at timestamptz not null default now()
);

create index governance_audit_logs_org_created_idx on governance_audit_logs (organization_id, created_at desc);
create index governance_audit_logs_workspace_idx on governance_audit_logs (workspace_id);

create table governance_timesheet_setups (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    member_user_id bigint not null references identity_users (id) on delete cascade,
    approver_user_id bigint references identity_users (id) on delete set null,
    approver_user_ids jsonb not null default '[]'::jsonb,
    approver_layers jsonb not null default '{}'::jsonb,
    periodicity text not null default 'weekly',
    reminder_day integer not null default 1,
    reminder_time text not null default '17:00',
    email_reminder_enabled boolean not null default false,
    slack_reminder_enabled boolean not null default false,
    start_date date not null,
    end_date date,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint governance_timesheet_setups_periodicity_check check (periodicity in ('daily', 'weekly', 'monthly')),
    constraint governance_timesheet_setups_reminder_day_check check (reminder_day between 0 and 6)
);

create index governance_timesheet_setups_workspace_id_idx on governance_timesheet_setups (workspace_id);
create index governance_timesheet_setups_member_user_id_idx on governance_timesheet_setups (member_user_id);

create table governance_timesheets (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    timesheet_setup_id bigint not null references governance_timesheet_setups (id) on delete cascade,
    member_user_id bigint not null references identity_users (id) on delete cascade,
    start_date date not null,
    end_date date not null,
    status text not null default 'open',
    force_approved boolean not null default false,
    rejection_comment text not null default '',
    review_layer integer not null default 0,
    submitted_at timestamptz,
    approved_or_rejected_at timestamptz,
    approved_or_rejected_id bigint references identity_users (id) on delete set null,
    reminder_sent_at timestamptz,
    timezone text not null default 'UTC',
    reviews jsonb not null default '[]'::jsonb,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint governance_timesheets_status_check check (status in ('open', 'submitted', 'approved', 'rejected', 'reopened'))
);

create unique index governance_timesheets_setup_start_key on governance_timesheets (timesheet_setup_id, start_date);
create index governance_timesheets_workspace_id_idx on governance_timesheets (workspace_id);
create index governance_timesheets_member_user_id_idx on governance_timesheets (member_user_id);

create table instance_admin_bootstrap (
    id integer primary key default 1,
    completed boolean not null default false,
    admin_email text not null default '',
    completed_at timestamptz,
    constraint instance_admin_bootstrap_singleton check (id = 1)
);

create table instance_admin_registration_policy (
    id integer primary key default 1,
    mode text not null default 'closed',
    updated_at timestamptz not null default now(),
    constraint instance_admin_registration_policy_singleton check (id = 1),
    constraint instance_admin_registration_policy_mode_check check (mode in ('open', 'closed', 'invite_only'))
);

create table instance_admin_config (
    id integer primary key default 1,
    site_url text not null default '',
    sender_email text not null default '',
    sender_name text not null default 'OpenTickly',
    smtp_host text not null default '',
    smtp_port integer not null default 0,
    smtp_username text not null default '',
    smtp_password text not null default '',
    email_verification_required boolean not null default false,
    updated_at timestamptz not null default now(),
    saml_sp_private_key text not null default '',
    saml_sp_certificate text not null default '',
    constraint instance_admin_config_singleton check (id = 1)
);

create table tenant_workspace_sso_config (
    workspace_id bigint primary key references tenant_workspaces(id) on delete cascade,
    enabled boolean not null default false,
    profile_name text not null default '',
    email_domain text not null default '',
    idp_metadata_url text not null default '',
    idp_entity_id text not null default '',
    idp_sso_url text not null default '',
    idp_certificate text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index tenant_workspace_sso_config_domain_key
    on tenant_workspace_sso_config (lower(email_domain))
    where enabled and email_domain <> '';

create table billing_invoices (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id),
    user_id bigint not null references identity_users (id),
    document_id text not null default '',
    billing_address text not null default '',
    workspace_address text not null default '',
    currency text not null default 'USD',
    date date not null default current_date,
    due_date date,
    message text not null default '',
    payment_terms text not null default '',
    purchase_number text not null default '',
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index billing_invoices_workspace_id_idx on billing_invoices (workspace_id);
create index billing_invoices_user_id_idx on billing_invoices (user_id);

create table billing_invoice_items (
    id bigint generated by default as identity primary key,
    invoice_id bigint not null references billing_invoices (id) on delete cascade,
    description text not null default '',
    quantity numeric(12,2) not null default 0,
    amount numeric(12,2) not null default 0
);

create index billing_invoice_items_invoice_id_idx on billing_invoice_items (invoice_id);

create table billing_invoice_taxes (
    id bigint generated by default as identity primary key,
    invoice_id bigint not null references billing_invoices (id) on delete cascade,
    name text not null default '',
    amount numeric(12,2) not null default 0
);

create index billing_invoice_taxes_invoice_id_idx on billing_invoice_taxes (invoice_id);

create table user_onboarding (
    user_id bigint primary key references identity_users (id) on delete cascade,
    completed_at timestamptz not null default now(),
    version integer not null default 1
);

-- Saved/shared reports: persisted report definitions that users can bookmark and share.
create table saved_reports (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null default '',
    public boolean not null default false,
    fixed_date_range boolean not null default false,
    token text,
    params jsonb not null default '{}',
    created_by bigint not null references identity_users (id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index saved_reports_workspace_id_idx on saved_reports (workspace_id);
create unique index saved_reports_token_idx on saved_reports (token) where token is not null;

-- Scheduled reports: recurring email delivery of saved reports.
create table scheduled_reports (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    report_id bigint not null references saved_reports (id) on delete cascade,
    frequency int not null default 1,
    creator_id bigint not null references identity_users (id),
    user_ids bigint[] not null default '{}',
    group_ids bigint[] not null default '{}',
    created_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index scheduled_reports_workspace_id_idx on scheduled_reports (workspace_id);
create index scheduled_reports_report_id_idx on scheduled_reports (report_id);

-- Webhook subscriptions: event notification delivery endpoints per workspace.
create table webhook_subscriptions (
    id bigserial primary key,
    workspace_id bigint not null,
    user_id bigint not null references identity_users (id) on delete cascade,
    description text not null,
    url_callback text not null,
    secret text not null,
    enabled boolean not null default false,
    validation_code text not null default '',
    validated_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create unique index webhook_subscriptions_description_workspace_unique
    on webhook_subscriptions (workspace_id, description) where (deleted_at is null);

create index webhook_subscriptions_workspace_id_idx
    on webhook_subscriptions (workspace_id) where (deleted_at is null);

create table file_blobs (
    storage_key text primary key,
    content_type text not null,
    content bytea not null,
    created_at timestamptz not null default now()
);

create table webhook_subscription_event_filters (
    id bigserial primary key,
    subscription_id bigint not null references webhook_subscriptions (id) on delete cascade,
    entity text not null,
    action text not null,
    constraint webhook_subscription_event_filters_unique
        unique (subscription_id, entity, action)
);

create index webhook_subscription_event_filters_subscription_id_idx
    on webhook_subscription_event_filters (subscription_id);

-- Singleton row carrying this self-hosted instance's stable identity. Used by
-- the telemetry pinger to report anonymous daily check-ins to the upstream
-- update service, and by the admin instance-version endpoint.
create table instance_identity (
    id smallint primary key default 1 check (id = 1),
    instance_id uuid not null default gen_random_uuid(),
    first_seen_at timestamptz not null default now()
);

-- Per-user external calendar OAuth integrations (Google Calendar for now).
-- One-way import only: OpenTickly reads events, never writes back. Soft
-- delete on disconnect preserves any time entries already created from a
-- calendar event.
create table calendar_integrations (
    id bigserial primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    provider text not null,
    email text not null default '',
    access_token text not null default '',
    refresh_token text not null default '',
    token_expires_at timestamptz,
    has_write_scope boolean not null default false,
    error_status text not null default '',
    scopes text[] not null default '{}',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create unique index calendar_integrations_user_provider_key
    on calendar_integrations (user_id, provider)
    where deleted_at is null;

create table calendar_integration_calendars (
    id bigserial primary key,
    calendar_integration_id bigint not null references calendar_integrations (id) on delete cascade,
    external_id text not null,
    name text not null default '',
    background_color text not null default '',
    foreground_color text not null default '',
    selected boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint calendar_integration_calendars_unique
        unique (calendar_integration_id, external_id)
);

create index calendar_integration_calendars_integration_id_idx
    on calendar_integration_calendars (calendar_integration_id);
